[build]
target = "avr-atmega32u4.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude leonardo -cb 57600 -P /dev/ttyACM0"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]